package rules;
import com.github.entity.Reading;
import com.github.entity.Vehicle;
import com.github.entity.Alert;
import com.github.entity.Tires;
import com.github.repository.VehicleRepository
import com.github.repository.AlertRepository
import org.springframework.beans.factory.annotation.Autowired;

rule "engine RPM"
	when
	    entityManager: AlertRepository()
	    alert: Alert()
	    reading: Reading()
	    vehicle: Vehicle(getVin() == reading.getVin(), getRedlineRpm() < reading.getEngineRpm())
	then

		alert.setPriority("High");
        alert.setReading(reading);
        entityManager.save(alert);
	end

rule "fuel Volume"
	when
	    entityManager: AlertRepository()
        alert: Alert()
	    reading: Reading()
	    vehicle: Vehicle(getVin() == reading.getVin(), (0.1 * getMaxFuelVolume()) > reading.getFuelVolume())
	then
		alert.setPriority("High");
        alert.setReading(reading);
        entityManager.save(alert);

	end

rule "tire Pressure"
	when
	    entityManager: AlertRepository()
	    alert: Alert()
	    reading: Reading()
	    tires: Tires(reading.getTires().frontLeft < 32 || reading.getTires().frontLeft > 36 || reading.getTires().rearLeft < 32 || reading.getTires().rearLeft > 36
	                    || reading.getTires().frontRight < 32 || reading.getTires().frontRight > 36 || reading.getTires().rearRight < 32 || reading.getTires().rearRight > 36)

	then

		alert.setPriority("High");
		alert.setReading(reading);
		entityManager.save(alert);

	end

rule "engine Condition"
	when
	    entityManager: AlertRepository()
        alert: Alert()
	    reading: Reading(reading.isCheckEngineLightOn() || reading.isEngineCoolantLow())

	then
		alert.setPriority("High");
		alert.setReading(reading);
		entityManager.save(alert);
	end

